### ISSUE TITLE
启用主题时报错

### ISSUE THREAD

**Issue by Yeyongmeng29** [SukkaW/hexo-theme-suka#12]
**I certify that I have first consulted** (check with "x")

**我确认我已经查看了** (选择时请使用 "x" 取代方括号中的空格)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Suka theme issues | Suka 主题的其它 issue](https://github.com/SukkaW/hexo-theme-suka/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

## 我正在申请  (选择时请使用 "x" 取代方括号中的空格)

- [x] bug report | 反馈一个 Bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

----

### Node.js 和 NPM 的相关信息

```
$ node -v; and npm -v #不要在意，我是 fish 用户
v10.6.0
6.3.0
```
### 依赖包相关信息

```
$ cat package.json
{
  "name": "hexo-theme-suka",
  "version": "0.0.1",
  "description": "Modern, powerful and simple theme for Hexo",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "setup": "npm cache clean && npm install",
    "lint": "bash lint.sh"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SukkaW/hexo-theme-suka.git"
  },
  "keywords": [
    "hexo",
    "hexo-theme",
    "suka",
    "sukkaw"
  ],
  "author": "SukkaW",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/SukkaW/hexo-theme-suka/issues"
  },
  "homepage": "https://github.com/SukkaW/hexo-theme-suka#readme",
  "devDependencies": {
    "ejs-lint": "^0.3.0",
    "eslint": "^5.0.1",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-clean-css": "^3.9.4",
    "gulp-rename": "^1.3.0",
    "gulp-uglify": "^3.0.0",
    "sass-lint": "^1.12.1"
  },
  "dependencies": {
    "json-stringify-safe": "^5.0.1",
    "node-prismjs": "^0.1.2",
    "prismjs": "^1.15.0",
    "qr-image": "^3.2.0"
  }
}
```

### Hexo 版本号

```
$ hexo -v
hexo: 3.7.1
hexo-cli: 1.1.0
os: Linux 4.17.12-1-default linux x64
http_parser: 2.8.0
node: 10.6.0
v8: 6.7.288.46-node.13
uv: 1.21.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.31.1
napi: 3
openssl: 1.1.0h-fips
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

### 站点配置文件和主题配置文件

*与配置文件无关，实测新建的 Hexo 博客也有此问题*

### 报错日志

运行 `hexo s --debug` ，至启动成功时无报错，访问 localhost:4000 时开始报错

```
Unhandled rejection TypeError: /home/yongmeng/Blog/themes/suka/layout/layout.ejs:4
    2|                                                                                                                                                       
    3| <html <% if(config.language) { %>lang="<%- config.language %>"<% } %>>                                                                                
 >> 4|     <%- partial('_partial/head/main') %>                                                                                                              
    5|                                                                                                                                                       
    6|     <body>                                                                                                                                            
    7|         <!-- ### Main content ### -->                                                                                                                 

/home/yongmeng/Blog/themes/suka/layout/_partial/head/main.ejs:23                                                                                             
    21|                                                                                                                                                      
    22|     <!-- ### RSS ### -->                                                                                                                             
 >> 23|     <%- partial('_partial/head/rss', {}, {cache: true}) %>                                                                                           
    24|                                                                                                                                                      
    25|     <!-- ### WebApp ### -->                                                                                                                          
    26|     <%- partial('_partial/head/webapp', {}, {cache: true}) %>                                                                                        

/home/yongmeng/Blog/themes/suka/layout/_partial/head/rss.ejs:1                                                                                               
 >> 1| <% if(config.feed.type) { %>                                                                                                                          
    2|     <% if(config.feed.type == "atom"){ %>                                                                                                             
    3|         <link rel="alternate" type="application/atom+xml" href="<%= url_for(config.feed.path) %>">                                                    
    4|     <% } else if(config.feed.type == "rss2") { %>                                                                                                     

Cannot read property 'type' of undefined                                                                                                                     
    at eval (eval at compile (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:23)                                                     
    at returnedFn (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:580:17)                                                                                   
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:120:22)                             
    at Theme._View.View.View.renderSync (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:48:23)                                                      
    at fragment_cache (/home/yongmeng/Blog/node_modules/hexo/lib/plugins/helper/partial.js:36:52)                                                            
    at Object.fragmentCache (/home/yongmeng/Blog/node_modules/hexo/lib/plugins/helper/fragment_cache.js:9:32)                                                
    at Object.wrapper [as fragment_cache] (/home/yongmeng/Blog/node_modules/lodash/lodash.js:4941:19)                                                        
    at Object.partial (/home/yongmeng/Blog/node_modules/hexo/lib/plugins/helper/partial.js:36:17)                                                            
    at Object.wrapper [as partial] (/home/yongmeng/Blog/node_modules/lodash/lodash.js:4941:19)                                                               
    at eval (eval at compile (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:29:17)
    at returnedFn (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/home/yongmeng/Blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/home/yongmeng/Blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/home/yongmeng/Blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled.locals [as _compiled] (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/home/yongmeng/Blog/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/home/yongmeng/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yongmeng/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/yongmeng/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/yongmeng/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/yongmeng/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/yongmeng/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/yongmeng/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yongmeng/Blog/node_modules/bluebird/js/release/async.js:17:14)
```
----

### 预期结果和你的实际结果

----

**Comment by SukkaW** [comment]
Please give me your hexo site's `package.json`

```bash
$ cd hexo
$ cat package.json
```

**Comment by Yeyongmeng29** [comment]
```
$ cat package.json

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "aplayer": "^1.10.1",
    "hexo": "^3.7.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-aplayer": "^3.0.4"
  }
}
```

**Comment by SukkaW** [comment]
Hey, I have just released the [new version of theme](https://github.com/SukkaW/hexo-theme-suka/releases/tag/1.0.1). Try update the theme to see if the bug was fixed?

I [run the theme unit test on Travis CI](https://travis-ci.org/SukkaW/hexo-theme-suka/builds/414357101) and the new version of theme has passed the test without any issue.

**Comment by SukkaW** [comment]
Also, I noticed that you are using `hexo-generator-search`. which is useless in suka theme. Suka theme has built in a search database generator.

**Comment by Yeyongmeng29** [comment]
情况现在有点复杂

**Comment by Yeyongmeng29** [comment]
情况有点复杂，抱歉我的英语水平已经无法描述

更新到 1.0.1 后，报错依旧，内容相同

我注意到了以下内容
```
Unhandled rejection TypeError: /home/yongmeng/Blog/themes/suka/layout/layout.ejs:4
    2|                                                                                                                                                       
    3| <html <% if(config.language) { %>lang="<%- config.language %>"<% } %>>                                                                                
 >> 4|     <%- partial('_partial/head/main') %>                                                                                                              
    5|                                                                                                                                                       
    6|     <body>                                                                                                                                            
    7|         <!-- ### Main content ### -->                                                                                                                 

/home/yongmeng/Blog/themes/suka/layout/_partial/head/main.ejs:23                                                                                             
    21|                                                                                                                                                      
    22|     <!-- ### RSS ### -->                                                                                                                             
 >> 23|     <%- partial('_partial/head/rss', {}, {cache: true}) %>                                                                                           
    24|                                                                                                                                                      
    25|     <!-- ### WebApp ### -->                                                                                                                          
    26|     <%- partial('_partial/head/webapp', {}, {cache: true}) %>                                                                                        

/home/yongmeng/Blog/themes/suka/layout/_partial/head/rss.ejs:1                                                                                               
 >> 1| <% if(config.feed.type) { %>                                                                                                                          
    2|     <% if(config.feed.type == "atom"){ %>                                                                                                             
    3|         <link rel="alternate" type="application/atom+xml" href="<%= url_for(config.feed.path) %>">                                                    
    4|     <% } else if(config.feed.type == "rss2") { %> 
```

死马当活马医一下，遂修改主题配置文件
```
nav:
  rss:
    use: false
```
 同时删除了 `layout/_partial/head/rss.ejs`
并在 `layout/layout.ejs` 第三行改为 `<html>`

Then it works…

**Comment by SukkaW** [comment]
I see...
I think you must don't have configured your site config properly.
Look at the [build log](https://travis-ci.org/SukkaW/hexo-theme-suka/builds/414357101) of automated test unit. It seems like well configured hexo can run normally without any problem. And sorry I have to close this issue. Hope you have read the docs properly.

**Comment by wujunze** [comment]
Mee To  
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```
